name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      options:
        - README
        - API Documentation
        - Getting Started Guide
        - Configuration Guide
        - Contributing Guide
        - Code Comments
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Which file or section needs improvement?
      placeholder: "e.g., docs/API.md, README.md#installation"

  - type: textarea
    id: issue
    attributes:
      label: What's the Issue?
      description: What's unclear, missing, or incorrect?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve it?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR for this improvement
