"""Type stubs for lancedb.table."""

from typing import Any

import lancedb
import pyarrow as pa

class Table:
    def add(self, data: list[dict[str, Any]]) -> None: ...
    def search(self, query: Any = ..., query_type: str = ...) -> lancedb.LanceQueryBuilder: ...
    def delete(self, predicate: str) -> None: ...
    def count_rows(self, predicate: str = ...) -> int: ...
    def create_index(
        self,
        column: str,
        config: Any = ...,
        index_type: str = ...,
        replace: bool = ...,
        **kwargs: Any,
    ) -> None: ...
    def create_fts_index(
        self,
        column: str,
        use_tantivy: bool = ...,
        with_position: bool = ...,
        **kwargs: Any,
    ) -> None: ...
    def list_indices(self) -> list[dict[str, Any]]: ...
    def compact_files(self) -> None: ...
    def optimize(self) -> None: ...
    def stats(self) -> dict[str, Any] | Any: ...
